
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_nether", 0.7, "MC"], ["aether:the_aether", -0.7, "MC"], ["minecraft:the_end", -0.3, "MC"]]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [["minecraft:beach", 5.0, 15.0, "C"], ["minecraft:jagged_peaks", -23.0, -11.0, "C"], ["minecraft:windswept_hills", -5.3, 6.7, "C"], ["minecraft:old_growth_pine_taiga", -3.8, 6.2, "C"], ["minecraft:cold_ocean", 17.0, 19.0, "C"], ["minecraft:warm_ocean", 27.0, 28.999999999999996, "C"], ["minecraft:deep_frozen_ocean", -15.5, -13.5, "C"], ["minecraft:ice_spikes", -23.0, -11.0, "C"], ["minecraft:savanna", 22.0, 34.0, "C"], ["minecraft:mangrove_swamp", 16.0, 22.0, "C"], ["minecraft:forest", 5.0, 15.0, "C"], ["minecraft:windswept_gravelly_hills", -5.3, 6.7, "C"], ["minecraft:eroded_badlands", 13.0, 25.0, "C"], ["minecraft:desert", 21.0, 35.0, "C"], ["minecraft:lukewarm_ocean", 23.0, 25.0, "C"], ["minecraft:sunflower_plains", 3.5000000000000004, 15.5, "C"], ["minecraft:dark_forest", 15.0, 23.0, "C"], ["minecraft:windswept_forest", 3.5000000000000004, 15.5, "C"], ["minecraft:ocean", 20.0, 22.0, "C"], ["minecraft:old_growth_birch_forest", -3.8, 6.2, "C"], ["minecraft:grove", -16.3, -8.3, "C"], ["minecraft:taiga", -3.8, 6.2, "C"], ["minecraft:old_growth_spruce_taiga", -3.8, -6.2, "C"], ["minecraft:cherry_grove", 14.000000000000002, 24.0, "C"], ["minecraft:stony_shore", 3.5000000000000004, 15.5, "C"], ["minecraft:stony_peaks", 3.5000000000000004, 15.5, "C"], ["minecraft:birch_forest", -5.3, 6.7, "C"], ["minecraft:swamp", 16.0, 22.0, "C"], ["minecraft:sparse_jungle", 15.0, 23.0, "C"], ["minecraft:river", 12.5, 20.5, "C"], ["minecraft:meadow", -5.3, 6.7, "C"], ["minecraft:jungle", 25.0, 31.0, "C"], ["minecraft:dripstone_caves", 18.0, 22.0, "C"], ["minecraft:savanna_plateau", 22.0, 34.0, "C"], ["minecraft:deep_ocean", 20.0, 22.0, "C"], ["minecraft:deep_lukewarm_ocean", 23.0, 25.0, "C"], ["minecraft:flower_forest", 5.0, 15.0, "C"], ["minecraft:snowy_slopes", -21.5, -11.5, "C"], ["minecraft:snowy_taiga", -17.8, -7.8, "C"], ["minecraft:snowy_beach", -17.8, -7.8, "C"], ["minecraft:wooded_badlands", 13.0, 25.0, "C"], ["minecraft:snowy_plains", -19.3, -7.3, "C"], ["minecraft:deep_dark", 3.5000000000000004, 15.5, "C"], ["minecraft:badlands", 13.0, 25.0, "C"], ["minecraft:plains", 3.5000000000000004, 15.5, "C"], ["minecraft:deep_cold_ocean", 17.0, 19.0, "C"], ["minecraft:bamboo_jungle", 15.0, 23.0, "C"], ["minecraft:mushroom_fields", 15.0, 23.0, "C"], ["minecraft:frozen_river", -14.800000000000002, -8.8, "C"], ["minecraft:lush_caves", 18.0, 22.0, "C"], ["minecraft:frozen_ocean", -17.0, -13.0, "C"], ["minecraft:windswept_savanna", 22.0, 34.0, "C"]]

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 0.6
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65.0, "F"]]
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["minecraft:campfire", "minecraft:soul_campfire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = [["minecraft:fortress", -0.2, "MC"]]

[Hearth]
	#How effective the hearth is at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.75
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:birch_leaves", "minecraft:oak_leaves", "minecraft:flowering_azalea_leaves", "minecraft:azalea_leaves", "minecraft:jungle_leaves", "gtceu:rubber_leaves", "minecraft:dark_oak_leaves", "minecraft:cherry_leaves", "minecraft:spruce_leaves", "minecraft:mangrove_leaves", "minecraft:acacia_leaves"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []
	#Allows the hearth to automatically turn on/off based on nearby players' temperature
	#If false, the hearth turns on/off by redstone signal
	"Automatic Hearth" = false

#Format: [season-start, season-mid, season-end]
#Applied as an offset to the world's temperature
["Season Temperatures"]
	Summer = [0.439, 0.6, 0.6]
	Autumn = [0.439, 0.161, -0.161]
	Winter = [-0.536, -0.793, -0.793]
	Spring = [-0.536, -0.161, 0.161]

[Blocks]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: The temperature of the block, in Minecraft units
	#*falloff: The block is less effective as distance increases
	#*max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	#*predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	#- (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	#*nbt: The NBT data that the block must have for the temperature to be applied.
	#*temperature-limit: The maximum world temperature at which this block temp will be effective.
	#- (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [["cold_sweat:boiler", 0.27, 7, 0.88, "lit=true", "", 4], ["cold_sweat:icebox", -0.27, 7, 0.88, "frosted=true", "", 0], ["minecraft:fire", 0.476, 7, 0.9, "", "", 8], ["#minecraft:campfires", 0.476, 7, 0.9, "lit=true", " ", 8], ["minecraft:magma_block", 0.25, 3, 1.0], ["minecraft:lava_cauldron", 0.5, 7, 1.5], ["minecraft:ice", -0.15, 4, 0.6, "", "", -0.7], ["minecraft:packed_ice", -0.25, 4, 1.0, "", "", -0.7], ["minecraft:blue_ice", -0.35, 4, 1.4, "", "", -0.7], ["#minecraft:ice", -0.15, 4, 0.6, "", "", -0.7]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Check" = true

